# Generated by Django 4.2 on 2025-09-10 02:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=200, verbose_name='lastName')),
                ('cpf', models.CharField(help_text='Digite Exatamente 11 números', max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='cpf')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(help_text='Digite exatamente 11 Números', max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='occupancy',
            name='nameOccupant',
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.occupant'),
        ),
    ]
