# Generated by Django 4.2 on 2025-09-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_occupant_remove_occupancy_nameoccupant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('interval', models.PositiveIntegerField(default=60)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
